services:
  postgres:
    image: postgres:16
    container_name: eka-postgres

    environment:
      POSTGRES_DB: EnterpriseKnowledgeAssistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres-data: